default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: little_shop_development

test:
  <<: *default
  database: little_shop_test

production:
  <<: *default
  database: little_shop_production
  username: little_shop
  password: <%= ENV['LITTLE_SHOP_DATABASE_PASSWORD'] %>
